#values-dev.yaml shop app
environment: dev  

frontend:
  image:
    repository: bansikah/shop-frontend
    tag: "1.2.0"
  replicaCount: 1
  pullPolicy: IfNotPresent
  env:
    REACT_APP_API_URL: "http://shop-app-dev.local/api"
  ports:
    - containerPort: 80
  nodeSelector:
    role: worker  

backend:
  image:
    repository: bansikah/shop-backend
    tag: "1.2.0"
  replicaCount: 1
  nodeSelector:
    role: worker  

postgres:
  image:
    repository: postgres
    tag: latest
  database: shopdb
  serviceType: NodePort
#removed user name and password
  nodeSelector:
    role: worker  

ingress:
  host: shop-app-dev.local
