apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.database | b64enc }}
  POSTGRES_USER: {{ if .Values.postgres.username }}{{ .Values.postgres.username | b64enc }}{{ else }}{{ randAlphaNum 8 | b64enc }}{{ end }}
  POSTGRES_PASSWORD: {{ if .Values.postgres.password }}{{ .Values.postgres.password | b64enc }}{{ else }}{{ randAlphaNum 12 | b64enc }}{{ end }}
