apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  type: {{ Values.postgres.serviceType}}
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432